[graphics]
resolution = "720p"
fullscreen = false
vsync = true
fsaa = "4x"
debug = true

[telemetry]
logging = "info"
profiling = false

[game]
sources = ["game.data", "game/", "common/"]
dev_mode = true